# ============================================================
# LAP Deployment Config
# ============================================================

# ============================================================
# Network
# ============================================================
remote_gripper_host: "192.168.0.56"
remote_gripper_port: 5009
remote_gripper_timeout: 30
